'use client';
import {useMemo,useState} from 'react';
const C={r:.075,n:2,s:3,v:2000,g:50000};
const f=x=>Math.round(Number(x||0)).toLocaleString('zh-TW');
const sp=d=>{let x=new Date(d).getDate();return x>=29||x<=5};
const opts=Array.from({length:20},(_,i)=>(i+1)*10000);
const baseCalc=(b,t,d,v,g,its)=>{let p=sp(d)?C.s:C.n;let i=Math.round(b*C.r*p);let vc=t==='vehicle'&&v?C.v:0;let gc=t==='gold'?Number(g||0):0;let o=its.reduce((a,x)=>a+Number(x.amount||0),0);let total=i+vc+gc+o;return{b,p,i,vc,gc,o,total,net:b-total}};
const backCalc=(target,t,d,v,g,its)=>{let p=sp(d)?C.s:C.n;let fixed=(t==='vehicle'&&v?C.v:0)+its.reduce((a,x)=>a+Number(x.amount||0),0);let raw=(Number(target||0)+fixed)/(1-C.r*p);let b=Math.ceil(raw/10000)*10000;return baseCalc(b,t,d,v,g,its)};
export default function Page(){let today=new Date().toISOString().slice(0,10);let[mode,setMode]=useState('loan'),[type,setTypeRaw]=useState('normal'),[date,setDate]=useState(today),[amount,setAmount]=useState(100000),[target,setTarget]=useState(97000),[veh,setVeh]=useState(false),[gold,setGold]=useState(''),[items,setItems]=useState([{name:'',amount:''}]);let setType=t=>{setTypeRaw(t);if(t==='gold')setMode('loan')};let r=useMemo(()=>mode==='loan'?baseCalc(type==='gold'?C.g:Number(amount||0),type,date,veh,gold,items):backCalc(target,type,date,veh,gold,items),[mode,type,date,amount,target,veh,gold,items]);let reset=()=>{if(!window.confirm('確定要清除所有資料重新計算嗎？'))return;setMode('loan');setTypeRaw('normal');setDate(today);setAmount(100000);setTarget(97000);setVeh(false);setGold('');setItems([{name:'',amount:''}])};let delItem=i=>{if(window.confirm('確定要刪除此扣款項目嗎？'))setItems(items.filter((_,n)=>n!==i))};let setItem=(i,k,v)=>setItems(items.map((x,n)=>n===i?{...x,[k]:v}:x));let getGold=async()=>{try{let a=await fetch('/api/gold-price');let j=await a.json();if(j.price>0)setGold(j.price)}catch(e){}};return <main className='page'></main>}
function Box(p){return <div className='card'><h2>{p.title}</h2>{p.children}</div>}
function Row({k,v,red,strong}){return <div className={(strong?'row strong':'row')+(red?' red':'')}><span>{k}</span><b>{v} 元</b></div>}