const $=id=>document.getElementById(id);
const list=[];
function today(){return new Date().toISOString().slice(0,10);}
function syncType(){const t=$('itemType').value;const isGold=t===ItemType.GOLD;$('vehicleSettingWrap').classList.toggle('hidden',t!==ItemType.VEHICLE);$('goldPriceWrap').classList.toggle('hidden',!isGold);$('loanAmount').disabled=isGold;if(isGold)$('loanAmount').value=DefaultSetting.goldFixedAmount;}
function renderList(){const box=$('deductionList');box.innerHTML='';list.forEach((x,i)=>{const row=document.createElement('div');row.className='deduction-row';row.innerHTML=`<input data-name="${i}" value="${x.name}" placeholder="扣款名稱"><input data-amount="${i}" type="number" min="0" step="1" value="${x.amount}" placeholder="金額"><label><input data-enabled="${i}" type="checkbox" ${x.enabled?'checked':''}>啟用</label><button data-del="${i}" type="button">刪除</button>`;box.appendChild(row);});}
function collect(){return{loanDate:$('loanDate').value,itemType:$('itemType').value,loanAmount:toNumber($('loanAmount').value),needVehicleSetting:$('needVehicleSetting').checked,goldPrice:toNumber($('goldPrice').value),deductions:list.filter(x=>x.enabled).map(x=>({name:x.name,amount:toNumber(x.amount)}))};}
function validate(input){if(!input.loanDate)return'請選擇放款日期';if(input.loanAmount<=0)return'放款金額需大於 0';if(input.itemType===ItemType.GOLD&&input.goldPrice<0)return'黃金價不可小於 0';for(const x of input.deductions){if(toNumber(x.amount)<0)return'其他扣款不可小於 0';}return'';}
function showError(msg){$('errorBox').textContent=msg;$('errorBox').classList.toggle('hidden',!msg);}
function line(k,v,c=''){return`<div class="result-line ${c}"><span>${k}</span><strong>${v}</strong></div>`;}
function renderResult(r,input){const p=$('resultPanel');const names=input.deductions.map(x=>`${x.name||'其他扣款'} ${money(x.amount)} 元`).join('<br>')||'無';p.innerHTML=`<h2>計算結果</h2>${line('放款金額',money(r.baseAmount)+' 元')}${line('前扣期數',r.periods+' 期')}${line('前扣利息',money(r.interest)+' 元')}${line('汽機車設定費',money(r.vehicleFee)+' 元')}${line('黃金一錢扣款',money(r.goldFee)+' 元')}${line('其他扣款合計',money(r.otherFee)+' 元')}<div class="small">${names}</div>${line('總扣款',money(r.totalDeduction)+' 元')}${line('客人實拿',money(r.netAmount)+' 元',r.netAmount<0?'total negative':'total positive')}`;p.classList.remove('hidden');}
function calculate(){LoanMachine.set(LoanState.VALIDATING);const input=collect();const err=validate(input);if(err){LoanMachine.set(LoanState.ERROR);showError(err);return;}showError('');LoanMachine.set(LoanState.CALCULATING);renderResult(calculateResult(input),input);LoanMachine.set(LoanState.RESULT);}
function bind(){document.addEventListener('input',e=>{const t=e.target;if(t.dataset.name!==undefined)list[Number(t.dataset.name)].name=t.value;if(t.dataset.amount!==undefined)list[Number(t.dataset.amount)].amount=t.value;if(t.dataset.enabled!==undefined)list[Number(t.dataset.enabled)].enabled=t.checked;});document.addEventListener('click',async e=>{const t=e.target;if(t.id==='addDeductionBtn'){list.push({name:'',amount:0,enabled:true});renderList();}if(t.dataset.del!==undefined){list.splice(Number(t.dataset.del),1);renderList();}if(t.id==='calculateBtn')calculate();if(t.id==='fetchGoldBtn'){LoanMachine.set(LoanState.AUTO_FETCHING_GOLD_PRICE);const v=await fetchGoldPrice();if(v>0){$('goldPrice').value=v;LoanMachine.set(LoanState.GOLD_PRICE_READY);}else LoanMachine.set(LoanState.GOLD_PRICE_FALLBACK);}});$('itemType').addEventListener('change',syncType);}
function init(){$('loanDate').value=today();bind();syncType();renderList();}
init();
